apiVersion: apps/v1
kind: Deployment

metadata:
  name: snake-game

spec:
  replicas: {{ .Values.replicaCount }}

  selector:
    matchLabels:
      app: snake-game

  template:
    metadata:
      labels:
        app: snake-game

    spec:
      containers:
      - name: snake-game
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"

        ports:
        - containerPort: 80
